"""followers

Revision ID: 950615ddb078
Revises: c4d28b7d2127
Create Date: 2019-03-06 15:22:13.207146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950615ddb078'
down_revision = 'c4d28b7d2127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
